### ISSUE TITLE
Crash with neumo-tune

### ISSUE THREAD

**Issue by andimik** [deeptho/blindscan#6]
Under Ubuntu 22.04 `neumo-tune` crashes:

Here is a `gdb` backtrace:

```
$ gdb ./neumo-tune 
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./neumo-tune...
(gdb) r
Starting program: /home/andreas/apps/blindscan/build/src/neumo-tune 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

adapter=0
rf_in=-1
frontend=0
freq=-1
pol=3
pls_codes[5]={ 4202496, 2048, 98139136, 134216704, 80015360, }
diseqc=UC: U=-1 C=-1
Blindscan drivers found
Name of card: TurboSight TBS 6903x 
Name of adapter: A0 TBS 6903X
Name of frontend: TurboSight TBS 6903x 
neumo-tune: /home/andreas/apps/blindscan/src/neumo-tune.cc:1264: int main_tune(int): Assertion `options.pol == 1 || options.pol == 2' failed.

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348118336) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348118336) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737348118336) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737348118336, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7a89476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7a6f7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7a6f71b in __assert_fail_base (fmt=0x7ffff7c24150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555555f80d3 "options.pol == 1 || options.pol == 2", 
    file=0x5555555f7a1f "/home/andreas/apps/blindscan/src/neumo-tune.cc", line=1264, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff7a80e96 in __GI___assert_fail (assertion=0x5555555f80d3 "options.pol == 1 || options.pol == 2", file=0x5555555f7a1f "/home/andreas/apps/blindscan/src/neumo-tune.cc", line=1264, 
    function=0x5555555f8285 "int main_tune(int)") at ./assert/assert.c:101
#7  0x0000555555564acd in main_tune (fefd=3) at /home/andreas/apps/blindscan/src/neumo-tune.cc:1264
#8  0x0000555555564ed8 in main (argc=1, argv=0x7fffffffe098) at /home/andreas/apps/blindscan/src/neumo-tune.cc:1335
(gdb) 

```

**Comment by deeptho** [comment]
Fixed in c8a58604d04f83fe848b242a544099667f5e6330
